name: hoalu-local

services:
  database:
    container_name: hoalu-db
    image: postgres:18-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    volumes:
      - pg_data:/var/lib/postgresql/18/docker

  electric:
    container_name: hoalu-electric
    image: electricsql/electric:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?sslmode=disable
      - ELECTRIC_PORT=4000
      - ELECTRIC_SECRET=${SYNC_SECRET}
    ports:
      - 4000:4000
    depends_on:
      - database
    volumes:
      - electric_data:/app/persistent

  redis:
    container_name: hoalu-redis
    image: redis:7.4.2-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

volumes:
  pg_data:
    driver: local
  electric_data:
    driver: local
