services:
  database:
    container_name: woben-db
    image: postgres:16-alpine
    restart: always
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    container_name: woben-electric
    image: electricsql/electric
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?sslmode=disable
    ports:
      - 4000:3000
    depends_on:
      - database
