name: woben

services:
  database:
    container_name: woben-db
    image: postgres:16-alpine
    restart: always
    networks:
      - woben_network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - pg_data:/var/lib/postgresql/data

  electric:
    container_name: woben-electric
    image: electricsql/electric
    restart: always
    networks:
      - woben_network
      - traefik_network
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable
      - ELECTRIC_PORT=4000
    depends_on:
      - database
    volumes:
      - electric_data:/app/persistent
    labels:
      - traefik.enable=true
      - traefik.http.routers.woben-sync.entrypoints=websecure
      - traefik.http.routers.woben-sync.rule=Host(`woben.local.${DOMAIN}`) && PathPrefix(`/sync`)
      - traefik.http.routers.woben-sync.tls=true
      - traefik.http.routers.woben-sync.tls.certresolver=cloudflare
      - traefik.http.routers.woben-sync.tls.domains[0].main=local.${DOMAIN}
      - traefik.http.routers.woben-sync.tls.domains[0].sans=*.local.${DOMAIN}
      - traefik.http.routers.woben-sync.middlewares=internal-gateway@file
      - traefik.http.routers.woben-sync.service=woben-sync
      - traefik.http.services.woben-sync.loadbalancer.server.port=4000

  server:
    container_name: woben-server
    build:
      context: ../
      dockerfile: ./deployments/server.Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    restart: always
    networks:
      - woben_network
      - traefik_network
    depends_on:
      - database
    labels:
      - traefik.enable=true
      - traefik.http.routers.woben-server.entrypoints=websecure
      - traefik.http.routers.woben-server.rule=Host(`woben.local.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.woben-server.tls=true
      - traefik.http.routers.woben-server.tls.certresolver=cloudflare
      - traefik.http.routers.woben-server.tls.domains[0].main=local.${DOMAIN}
      - traefik.http.routers.woben-server.tls.domains[0].sans=*.local.${DOMAIN}
      - traefik.http.routers.woben-server.middlewares=internal-gateway@file
      - traefik.http.routers.woben-server.service=woben-server
      - traefik.http.services.woben-server.loadbalancer.server.port=3000

  web:
    container_name: woben-web
    build:
      context: ../
      dockerfile: ./deployments/web.Dockerfile
      args:
        - PUBLIC_API_URL=${PUBLIC_API_URL}
        - PUBLIC_SYNC_URL=${PUBLIC_SYNC_URL}
    restart: always
    networks:
      - woben_network
      - traefik_network
    depends_on:
      - database
      - electric
      - server
    labels:
      - traefik.enable=true
      - traefik.http.routers.woben-web.entrypoints=websecure
      - traefik.http.routers.woben-web.rule=Host(`woben.local.${DOMAIN}`)
      - traefik.http.routers.woben-web.tls=true
      - traefik.http.routers.woben-web.tls.certresolver=cloudflare
      - traefik.http.routers.woben-web.tls.domains[0].main=local.${DOMAIN}
      - traefik.http.routers.woben-web.tls.domains[0].sans=*.local.${DOMAIN}
      - traefik.http.routers.woben-web.middlewares=internal-gateway@file
      - traefik.http.routers.woben-web.service=woben-web
      - traefik.http.services.woben-web.loadbalancer.server.port=8080

  migration:
    container_name: woben-migration
    build:
      context: ../
      dockerfile: ./deployments/migration.Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    restart: on-failure
    networks:
      - woben_network
    depends_on:
      - database

volumes:
  pg_data:
    driver: local
  electric_data:
    driver: local

networks:
  woben_network:
    name: woben_network
    driver: bridge
  traefik_network:
    external: true
