name: hoalu

services:
  database:
    container_name: hoalu-db
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    container_name: hoalu-electric
    image: electricsql/electric:latest
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?sslmode=disable
      - ELECTRIC_PORT=4000
    ports:
      - 4000:4000
    depends_on:
      - database

  migration:
    container_name: hoalu-migration
    build:
      context: ../
      dockerfile: ./deployments/migration.Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
    restart: on-failure
    depends_on:
      - database
