services:
  database:
    container_name: woben_db
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    container_name: woben_electric
    image: electricsql/electric
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?sslmode=disable
    ports:
      - 4000:3000
    depends_on:
      - database
