services:
  database:
    container_name: woben-db
    image: postgres:16
    restart: always
    networks:
      - woben_network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    # healthcheck:
    #   test: pg_isready --dbname='${DB_NAME}' --username='${DB_USER}'
    #   interval: 5m
    volumes:
      - ../pg-data:/var/lib/postgresql/data

  electric:
    container_name: woben-electric
    image: electricsql/electric
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - database

  app:
    container_name: woben-app
    build:
      context: ../
      dockerfile: ./deployments/app.Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    restart: always
    networks:
      - woben_network
      - traefik_network
    depends_on:
      - database
      - electric
    labels:
      - traefik.enable=true
      - traefik.http.routers.woben.entrypoints=websecure
      - traefik.http.routers.woben.rule=Host(`woben.local.${DOMAIN}`)
      - traefik.http.routers.woben.tls=true
      - traefik.http.routers.woben.tls.certresolver=cloudflare
      - traefik.http.routers.woben.tls.domains[0].main=local.${DOMAIN}
      - traefik.http.routers.woben.tls.domains[0].sans=*.local.${DOMAIN}
      - traefik.http.routers.woben.middlewares=internal-gateway@file
      - traefik.http.routers.woben.service=woben
      - traefik.http.services.woben.loadbalancer.server.port=3000

  migration:
    container_name: woben-migration
    build:
      context: ../
      dockerfile: ./deployments/migration.Dockerfile
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
    restart: on-failure
    networks:
      - woben_network
    depends_on:
      - database

networks:
  woben_network:
    name: woben_network
    driver: bridge
  traefik_network:
    external: true
