name: woben

services:
  database:
    container_name: woben-db
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
