/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as AuthImport } from './routes/_auth'
import { Route as DashboardIndexImport } from './routes/_dashboard/index'
import { Route as DashboardSlugImport } from './routes/_dashboard/$slug'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as DashboardSlugIndexImport } from './routes/_dashboard/$slug/index'
import { Route as InviteIdAcceptImport } from './routes/invite.$id.accept'
import { Route as DashboardAccountTokensImport } from './routes/_dashboard/account/tokens'
import { Route as DashboardAccountPreferencesImport } from './routes/_dashboard/account/preferences'
import { Route as DashboardSlugTasksImport } from './routes/_dashboard/$slug/tasks'
import { Route as DashboardSlugSettingsImport } from './routes/_dashboard/$slug/settings'
import { Route as DashboardSlugMembersImport } from './routes/_dashboard/$slug/members'
import { Route as DashboardSlugFinanceImport } from './routes/_dashboard/$slug/finance'
import { Route as DashboardSlugFinanceIndexImport } from './routes/_dashboard/$slug/finance/index'
import { Route as DashboardSlugFinanceWalletsImport } from './routes/_dashboard/$slug/finance/wallets'
import { Route as DashboardSlugFinanceExpensesImport } from './routes/_dashboard/$slug/finance/expenses'
import { Route as DashboardSlugFinanceCategoriesImport } from './routes/_dashboard/$slug/finance/categories'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSlugRoute = DashboardSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const DashboardSlugIndexRoute = DashboardSlugIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSlugRoute,
} as any)

const InviteIdAcceptRoute = InviteIdAcceptImport.update({
  id: '/invite/$id/accept',
  path: '/invite/$id/accept',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAccountTokensRoute = DashboardAccountTokensImport.update({
  id: '/account/tokens',
  path: '/account/tokens',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAccountPreferencesRoute =
  DashboardAccountPreferencesImport.update({
    id: '/account/preferences',
    path: '/account/preferences',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardSlugTasksRoute = DashboardSlugTasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardSlugRoute,
} as any)

const DashboardSlugSettingsRoute = DashboardSlugSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardSlugRoute,
} as any)

const DashboardSlugMembersRoute = DashboardSlugMembersImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardSlugRoute,
} as any)

const DashboardSlugFinanceRoute = DashboardSlugFinanceImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardSlugRoute,
} as any)

const DashboardSlugFinanceIndexRoute = DashboardSlugFinanceIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSlugFinanceRoute,
} as any)

const DashboardSlugFinanceWalletsRoute =
  DashboardSlugFinanceWalletsImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => DashboardSlugFinanceRoute,
  } as any)

const DashboardSlugFinanceExpensesRoute =
  DashboardSlugFinanceExpensesImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => DashboardSlugFinanceRoute,
  } as any)

const DashboardSlugFinanceCategoriesRoute =
  DashboardSlugFinanceCategoriesImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardSlugFinanceRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_dashboard/$slug': {
      id: '/_dashboard/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof DashboardSlugImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/$slug/finance': {
      id: '/_dashboard/$slug/finance'
      path: '/finance'
      fullPath: '/$slug/finance'
      preLoaderRoute: typeof DashboardSlugFinanceImport
      parentRoute: typeof DashboardSlugImport
    }
    '/_dashboard/$slug/members': {
      id: '/_dashboard/$slug/members'
      path: '/members'
      fullPath: '/$slug/members'
      preLoaderRoute: typeof DashboardSlugMembersImport
      parentRoute: typeof DashboardSlugImport
    }
    '/_dashboard/$slug/settings': {
      id: '/_dashboard/$slug/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof DashboardSlugSettingsImport
      parentRoute: typeof DashboardSlugImport
    }
    '/_dashboard/$slug/tasks': {
      id: '/_dashboard/$slug/tasks'
      path: '/tasks'
      fullPath: '/$slug/tasks'
      preLoaderRoute: typeof DashboardSlugTasksImport
      parentRoute: typeof DashboardSlugImport
    }
    '/_dashboard/account/preferences': {
      id: '/_dashboard/account/preferences'
      path: '/account/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof DashboardAccountPreferencesImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/account/tokens': {
      id: '/_dashboard/account/tokens'
      path: '/account/tokens'
      fullPath: '/account/tokens'
      preLoaderRoute: typeof DashboardAccountTokensImport
      parentRoute: typeof DashboardImport
    }
    '/invite/$id/accept': {
      id: '/invite/$id/accept'
      path: '/invite/$id/accept'
      fullPath: '/invite/$id/accept'
      preLoaderRoute: typeof InviteIdAcceptImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/$slug/': {
      id: '/_dashboard/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof DashboardSlugIndexImport
      parentRoute: typeof DashboardSlugImport
    }
    '/_dashboard/$slug/finance/categories': {
      id: '/_dashboard/$slug/finance/categories'
      path: '/categories'
      fullPath: '/$slug/finance/categories'
      preLoaderRoute: typeof DashboardSlugFinanceCategoriesImport
      parentRoute: typeof DashboardSlugFinanceImport
    }
    '/_dashboard/$slug/finance/expenses': {
      id: '/_dashboard/$slug/finance/expenses'
      path: '/expenses'
      fullPath: '/$slug/finance/expenses'
      preLoaderRoute: typeof DashboardSlugFinanceExpensesImport
      parentRoute: typeof DashboardSlugFinanceImport
    }
    '/_dashboard/$slug/finance/wallets': {
      id: '/_dashboard/$slug/finance/wallets'
      path: '/wallets'
      fullPath: '/$slug/finance/wallets'
      preLoaderRoute: typeof DashboardSlugFinanceWalletsImport
      parentRoute: typeof DashboardSlugFinanceImport
    }
    '/_dashboard/$slug/finance/': {
      id: '/_dashboard/$slug/finance/'
      path: '/'
      fullPath: '/$slug/finance/'
      preLoaderRoute: typeof DashboardSlugFinanceIndexImport
      parentRoute: typeof DashboardSlugFinanceImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardSlugFinanceRouteChildren {
  DashboardSlugFinanceCategoriesRoute: typeof DashboardSlugFinanceCategoriesRoute
  DashboardSlugFinanceExpensesRoute: typeof DashboardSlugFinanceExpensesRoute
  DashboardSlugFinanceWalletsRoute: typeof DashboardSlugFinanceWalletsRoute
  DashboardSlugFinanceIndexRoute: typeof DashboardSlugFinanceIndexRoute
}

const DashboardSlugFinanceRouteChildren: DashboardSlugFinanceRouteChildren = {
  DashboardSlugFinanceCategoriesRoute: DashboardSlugFinanceCategoriesRoute,
  DashboardSlugFinanceExpensesRoute: DashboardSlugFinanceExpensesRoute,
  DashboardSlugFinanceWalletsRoute: DashboardSlugFinanceWalletsRoute,
  DashboardSlugFinanceIndexRoute: DashboardSlugFinanceIndexRoute,
}

const DashboardSlugFinanceRouteWithChildren =
  DashboardSlugFinanceRoute._addFileChildren(DashboardSlugFinanceRouteChildren)

interface DashboardSlugRouteChildren {
  DashboardSlugFinanceRoute: typeof DashboardSlugFinanceRouteWithChildren
  DashboardSlugMembersRoute: typeof DashboardSlugMembersRoute
  DashboardSlugSettingsRoute: typeof DashboardSlugSettingsRoute
  DashboardSlugTasksRoute: typeof DashboardSlugTasksRoute
  DashboardSlugIndexRoute: typeof DashboardSlugIndexRoute
}

const DashboardSlugRouteChildren: DashboardSlugRouteChildren = {
  DashboardSlugFinanceRoute: DashboardSlugFinanceRouteWithChildren,
  DashboardSlugMembersRoute: DashboardSlugMembersRoute,
  DashboardSlugSettingsRoute: DashboardSlugSettingsRoute,
  DashboardSlugTasksRoute: DashboardSlugTasksRoute,
  DashboardSlugIndexRoute: DashboardSlugIndexRoute,
}

const DashboardSlugRouteWithChildren = DashboardSlugRoute._addFileChildren(
  DashboardSlugRouteChildren,
)

interface DashboardRouteChildren {
  DashboardSlugRoute: typeof DashboardSlugRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountPreferencesRoute: typeof DashboardAccountPreferencesRoute
  DashboardAccountTokensRoute: typeof DashboardAccountTokensRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSlugRoute: DashboardSlugRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountPreferencesRoute: DashboardAccountPreferencesRoute,
  DashboardAccountTokensRoute: DashboardAccountTokensRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof DashboardRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$slug': typeof DashboardSlugRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/$slug/finance': typeof DashboardSlugFinanceRouteWithChildren
  '/$slug/members': typeof DashboardSlugMembersRoute
  '/$slug/settings': typeof DashboardSlugSettingsRoute
  '/$slug/tasks': typeof DashboardSlugTasksRoute
  '/account/preferences': typeof DashboardAccountPreferencesRoute
  '/account/tokens': typeof DashboardAccountTokensRoute
  '/invite/$id/accept': typeof InviteIdAcceptRoute
  '/$slug/': typeof DashboardSlugIndexRoute
  '/$slug/finance/categories': typeof DashboardSlugFinanceCategoriesRoute
  '/$slug/finance/expenses': typeof DashboardSlugFinanceExpensesRoute
  '/$slug/finance/wallets': typeof DashboardSlugFinanceWalletsRoute
  '/$slug/finance/': typeof DashboardSlugFinanceIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof DashboardIndexRoute
  '/$slug/members': typeof DashboardSlugMembersRoute
  '/$slug/settings': typeof DashboardSlugSettingsRoute
  '/$slug/tasks': typeof DashboardSlugTasksRoute
  '/account/preferences': typeof DashboardAccountPreferencesRoute
  '/account/tokens': typeof DashboardAccountTokensRoute
  '/invite/$id/accept': typeof InviteIdAcceptRoute
  '/$slug': typeof DashboardSlugIndexRoute
  '/$slug/finance/categories': typeof DashboardSlugFinanceCategoriesRoute
  '/$slug/finance/expenses': typeof DashboardSlugFinanceExpensesRoute
  '/$slug/finance/wallets': typeof DashboardSlugFinanceWalletsRoute
  '/$slug/finance': typeof DashboardSlugFinanceIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/$slug': typeof DashboardSlugRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/$slug/finance': typeof DashboardSlugFinanceRouteWithChildren
  '/_dashboard/$slug/members': typeof DashboardSlugMembersRoute
  '/_dashboard/$slug/settings': typeof DashboardSlugSettingsRoute
  '/_dashboard/$slug/tasks': typeof DashboardSlugTasksRoute
  '/_dashboard/account/preferences': typeof DashboardAccountPreferencesRoute
  '/_dashboard/account/tokens': typeof DashboardAccountTokensRoute
  '/invite/$id/accept': typeof InviteIdAcceptRoute
  '/_dashboard/$slug/': typeof DashboardSlugIndexRoute
  '/_dashboard/$slug/finance/categories': typeof DashboardSlugFinanceCategoriesRoute
  '/_dashboard/$slug/finance/expenses': typeof DashboardSlugFinanceExpensesRoute
  '/_dashboard/$slug/finance/wallets': typeof DashboardSlugFinanceWalletsRoute
  '/_dashboard/$slug/finance/': typeof DashboardSlugFinanceIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/signup'
    | '/$slug'
    | '/'
    | '/$slug/finance'
    | '/$slug/members'
    | '/$slug/settings'
    | '/$slug/tasks'
    | '/account/preferences'
    | '/account/tokens'
    | '/invite/$id/accept'
    | '/$slug/'
    | '/$slug/finance/categories'
    | '/$slug/finance/expenses'
    | '/$slug/finance/wallets'
    | '/$slug/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/signup'
    | '/'
    | '/$slug/members'
    | '/$slug/settings'
    | '/$slug/tasks'
    | '/account/preferences'
    | '/account/tokens'
    | '/invite/$id/accept'
    | '/$slug'
    | '/$slug/finance/categories'
    | '/$slug/finance/expenses'
    | '/$slug/finance/wallets'
    | '/$slug/finance'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/$slug'
    | '/_dashboard/'
    | '/_dashboard/$slug/finance'
    | '/_dashboard/$slug/members'
    | '/_dashboard/$slug/settings'
    | '/_dashboard/$slug/tasks'
    | '/_dashboard/account/preferences'
    | '/_dashboard/account/tokens'
    | '/invite/$id/accept'
    | '/_dashboard/$slug/'
    | '/_dashboard/$slug/finance/categories'
    | '/_dashboard/$slug/finance/expenses'
    | '/_dashboard/$slug/finance/wallets'
    | '/_dashboard/$slug/finance/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  InviteIdAcceptRoute: typeof InviteIdAcceptRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  InviteIdAcceptRoute: InviteIdAcceptRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_dashboard",
        "/invite/$id/accept"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/signup"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/$slug",
        "/_dashboard/",
        "/_dashboard/account/preferences",
        "/_dashboard/account/tokens"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/_dashboard/$slug": {
      "filePath": "_dashboard/$slug.tsx",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/$slug/finance",
        "/_dashboard/$slug/members",
        "/_dashboard/$slug/settings",
        "/_dashboard/$slug/tasks",
        "/_dashboard/$slug/"
      ]
    },
    "/_dashboard/": {
      "filePath": "_dashboard/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/$slug/finance": {
      "filePath": "_dashboard/$slug/finance.tsx",
      "parent": "/_dashboard/$slug",
      "children": [
        "/_dashboard/$slug/finance/categories",
        "/_dashboard/$slug/finance/expenses",
        "/_dashboard/$slug/finance/wallets",
        "/_dashboard/$slug/finance/"
      ]
    },
    "/_dashboard/$slug/members": {
      "filePath": "_dashboard/$slug/members.tsx",
      "parent": "/_dashboard/$slug"
    },
    "/_dashboard/$slug/settings": {
      "filePath": "_dashboard/$slug/settings.tsx",
      "parent": "/_dashboard/$slug"
    },
    "/_dashboard/$slug/tasks": {
      "filePath": "_dashboard/$slug/tasks.tsx",
      "parent": "/_dashboard/$slug"
    },
    "/_dashboard/account/preferences": {
      "filePath": "_dashboard/account/preferences.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/account/tokens": {
      "filePath": "_dashboard/account/tokens.tsx",
      "parent": "/_dashboard"
    },
    "/invite/$id/accept": {
      "filePath": "invite.$id.accept.tsx"
    },
    "/_dashboard/$slug/": {
      "filePath": "_dashboard/$slug/index.tsx",
      "parent": "/_dashboard/$slug"
    },
    "/_dashboard/$slug/finance/categories": {
      "filePath": "_dashboard/$slug/finance/categories.tsx",
      "parent": "/_dashboard/$slug/finance"
    },
    "/_dashboard/$slug/finance/expenses": {
      "filePath": "_dashboard/$slug/finance/expenses.tsx",
      "parent": "/_dashboard/$slug/finance"
    },
    "/_dashboard/$slug/finance/wallets": {
      "filePath": "_dashboard/$slug/finance/wallets.tsx",
      "parent": "/_dashboard/$slug/finance"
    },
    "/_dashboard/$slug/finance/": {
      "filePath": "_dashboard/$slug/finance/index.tsx",
      "parent": "/_dashboard/$slug/finance"
    }
  }
}
ROUTE_MANIFEST_END */
